### ISSUE TITLE
Inquiries about articles

### ISSUE THREAD

**Issue by yezichu** [gloewing/causal_opto#1]
Since nips submissions have ended, I'm looking forward to having you upload your work to arxiv. I am very interested in the application of causal inference in closed-loop! Thanks a lot!

**Comment by gloewing** [comment]
Hi Yezi,

Thanks so much for your interest in our work! Here is our arxiv paper. Feel
free to reach out with any questions!

http://arxiv.org/abs/2405.18597

All the best,
Gabe

**Comment by gloewing** [comment]
Hi Yezi,

Thanks for your interest in our work! Here is our arxiv paper. Feel free to
reach out with any questions.

http://arxiv.org/abs/2405.18597

All the best,
Gabe
